export const materials_ru = [
	{
		category: 'text & audio',
		img: 'dialogue.jpg',
		title: 'dialogues',
		section: 'dialogue',
		text: 'Nos dialogues utilisent des tournures de phrases actuelles dans des situations variées. Ils vous aideront à maîtriser la langue parlée par les Russes au quotidien.',
	},
	{
		category: 'text & audio',
		img: 'slice-of-life.jpg',
		title: 'tranches de vie',
		section: 'slice-of-life',
		text: 'Vous trouverez ici de courts récits autobiographiques qui vous apprendrons à parler de vous, de votre entourage, de vos goûts et de vos sentiments.',
	},
	{
		category: 'text & audio',
		img: 'place.jpg',
		title: 'beaux endroits',
		section: 'place',
		text: 'La Russie est un vaste pays qui compte parmi les plus beaux endroits de la planète. Nous vous emmenons pour une visite passionnante qui vous donnera l’occasion de pratiquer la langue tout en vous émerveillant.',
	},
	{
		category: 'text & audio',
		img: 'culture.jpg',
		title: 'culture',
		section: 'culture',
		text: "La culture et le folklore changent d'un pays à l'autre et forgent l'identité des peuples. Dans cette section vous en saurez plus sur les particularités de la culture , du folklore et de l'artisanat russe.",
	},
	{
		category: 'text & audio',
		img: 'legends.jpg',
		title: 'légendes et folklore',
		section: 'legend',
		text: "La culture et le folklore changent d'un pays à l'autre et forgent l'identité des peuples. Dans cette section vous en saurez plus sur les particularités de la culture , du folklore et de l'artisanat russe.",
	},
	{
		category: 'text & audio',
		img: 'podcast.jpg',
		title: 'podcast',
		section: 'podcast',
		text: 'Avec nos podcast apprenez-en plus sur les particularités de la langue russe.',
	},
	{
		category: 'text & audio',
		img: 'audiobook.jpg',
		title: 'livres audio',
		section: 'book',
		text: 'Ici vous trouverez des livres audio accompagnés de leur texte. Ainsi vous élargirez votre vocabulaire et améliorerez votre compréhension orale tout en voyageant dans le monde passionnant de la littérature.',
	},
	{
		category: 'text & audio',
		img: 'short-story.jpg',
		title: 'histoires courtes',
		section: 'short-story',
		text: "Les histoires courtes ont le même objectif que les livres audio, mais sont plus condensées. Idéal pour ceux d'entre vous qui ne souhaitent pas se plonger dans un livre de plusieurs chapitres.",
	},
	{
		category: 'video',
		img: 'trailer.jpg',
		title: 'bandes annonces',
		section: 'trailer',
		text: "Avec les bandes annonces de films, vous disposez d'un moyen ludique pour vous entraîner à la compréhension orale du russe.",
	},
	{
		category: 'video',
		img: 'extract.jpg',
		title: 'extraits de films',
		section: 'extract',
		text: "Avec les extraits de films russes vous travaillerez votre compréhension de la langue telle que les Russes la parle au quotidien, faite d'idiomes, de jargon, mais surtout d'émotions.",
	},
	{
		category: 'video',
		img: 'cartoon.jpg',
		title: 'dessins animés',
		section: 'cartoon',
		text: 'Les dessins animés russes font partie de la culture du pays. Les Russes y font souvent référence dans leurs conversations et les connaître vous permettra d’être considéré par les Russes comme l’un des leurs.',
	},
	{
		category: 'video',
		img: 'eralash.jpg',
		title: 'eralash',
		section: 'eralash',
		text: 'Eralash est une série de sketch humoristiques mettant en scène des enfants. Fraîches et drôles, ces petites saynètes vous feront apprendre dans la bonne humeur.',
	},
	{
		category: 'video',
		img: 'galileo.jpg',
		title: 'galileo',
		section: 'galileo',
		text: "Galileo est une émission de vulgarisation très populaire en Russie. Son présentateur déjanté y aborde des thèmes aussi variés que l'art, la science, la technologie, le sport, l'alimentation etc. Grâce à la grande variété des sujets traités, vous élargirez votre vocabulaire tout en vous cultivant.",
	},
	{
		category: 'video',
		img: 'diverse.jpg',
		title: 'divers',
		section: 'diverse',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
	{
		category: 'music',
		img: 'rock.jpg',
		title: 'rock',
		section: 'rock',
		text: "Ces chansons russes accompagnées de leur texte vous permettront d'apprendre tout en vous divertissant.",
	},
	{
		category: 'music',
		img: 'pop.jpg',
		title: 'pop',
		section: 'pop',
		text: 'Les dessins animés russes font partie de la culture du pays. Les Russes y font souvent référence dans leurs conversations et les connaître vous permettra d’être considéré par les Russes comme l’un des leurs.',
	},
	{
		category: 'music',
		img: 'trad.jpg',
		title: 'trad/folk',
		section: 'trad',
		text: "Galileo est une émission de vulgarisation très populaire en Russie. Son présentateur déjanté y aborde des thèmes aussi variés que l'art, la science, la technologie, le sport, l'alimentation etc. Grâce à la grande variété des sujets traités, vous élargirez votre vocabulaire tout en vous cultivant.",
	},
	{
		category: 'music',
		img: 'variety.jpg',
		title: 'variété',
		section: 'variety',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
	{
		category: 'music',
		img: 'kids.jpg',
		title: 'enfants',
		section: 'kids',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
]

export const materials_fr = [
	{
		category: 'text & audio',
		img: 'dialogue.jpg',
		title: 'Диалоги',
		section: 'dialogue',
		text: 'Nos dialogues utilisent des tournures de phrases actuelles dans des situations variées. Ils vous aideront à maîtriser la langue parlée par les Russes au quotidien.',
	},
	{
		category: 'text & audio',
		img: 'slice-of-life.jpg',
		title: 'Кусочки жизни',
		section: 'slice-of-life',
		text: 'Vous trouverez ici de courts récits autobiographiques qui vous apprendrons à parler de vous, de votre entourage, de vos goûts et de vos sentiments.',
	},
	{
		category: 'text & audio',
		img: 'place.jpg',
		title: 'Красивые места',
		section: 'place',
		text: 'La Russie est un vaste pays qui compte parmi les plus beaux endroits de la planète. Nous vous emmenons pour une visite passionnante qui vous donnera l’occasion de pratiquer la langue tout en vous émerveillant.',
	},
	{
		category: 'text & audio',
		img: 'culture.jpg',
		title: 'Культура',
		section: 'culture',
		text: "La culture et le folklore changent d'un pays à l'autre et forgent l'identité des peuples. Dans cette section vous en saurez plus sur les particularités de la culture , du folklore et de l'artisanat russe.",
	},
	{
		category: 'text & audio',
		img: 'legends.jpg',
		title: 'Фольклор и легенды',
		section: 'legend',
		text: "La culture et le folklore changent d'un pays à l'autre et forgent l'identité des peuples. Dans cette section vous en saurez plus sur les particularités de la culture , du folklore et de l'artisanat russe.",
	},
	{
		category: 'text & audio',
		img: 'audiobook.jpg',
		title: 'Аудиокниги',
		section: 'book',
		text: 'Ici vous trouverez des livres audio accompagnés de leur texte. Ainsi vous élargirez votre vocabulaire et améliorerez votre compréhension orale tout en voyageant dans le monde passionnant de la littérature.',
	},
	{
		category: 'video',
		img: 'trailer.jpg',
		title: 'Трейлеры',
		section: 'trailer',
		text: "Avec les bandes annonces de films, vous disposez d'un moyen ludique pour vous entraîner à la compréhension orale du russe.",
	},
	{
		category: 'video',
		img: 'extract.jpg',
		title: 'Фрагменты из фильмов',
		section: 'extract',
		text: "Avec les extraits de films russes vous travaillerez votre compréhension de la langue telle que les Russes la parle au quotidien, faite d'idiomes, de jargon, mais surtout d'émotions.",
	},
	{
		category: 'video',
		img: 'cartoon.jpg',
		title: 'Мультфильмы',
		section: 'cartoon',
		text: 'Les dessins animés russes font partie de la culture du pays. Les Russes y font souvent référence dans leurs conversations et les connaître vous permettra d’être considéré par les Russes comme l’un des leurs.',
	},

	{
		category: 'video',
		img: 'diverse.jpg',
		title: 'Разное',
		section: 'diverse',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
	{
		category: 'music',
		img: 'rock.jpg',
		title: 'Рок',
		section: 'rock',
		text: "Ces chansons russes accompagnées de leur texte vous permettront d'apprendre tout en vous divertissant.",
	},
	{
		category: 'music',
		img: 'pop.jpg',
		title: 'Поп',
		section: 'pop',
		text: 'Les dessins animés russes font partie de la culture du pays. Les Russes y font souvent référence dans leurs conversations et les connaître vous permettra d’être considéré par les Russes comme l’un des leurs.',
	},
	{
		category: 'music',
		img: 'trad.jpg',
		title: 'Традиционная музыка и Фольк',
		section: 'trad',
		text: "Galileo est une émission de vulgarisation très populaire en Russie. Son présentateur déjanté y aborde des thèmes aussi variés que l'art, la science, la technologie, le sport, l'alimentation etc. Grâce à la grande variété des sujets traités, vous élargirez votre vocabulaire tout en vous cultivant.",
	},
	{
		category: 'music',
		img: 'variety.jpg',
		title: 'Хиты',
		section: 'variety',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
	{
		category: 'music',
		img: 'kids.jpg',
		title: 'Детские песни',
		section: 'kids',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
]

export const lang = ['ru', 'fr']
export const level = ['débutant', 'intermédiaire', 'avancé']
export const postData = {
	lang: 'ru',
	title: '',
	img: '',
	body: '',
	description: '',
}

export const materialData = {
	lang: 'ru',
	section: '',
	book_name: '',
	book_chapter: '',
	level: '',
	title: '',
	img: '',
	audio: '',
	video: '',
	body: '',
	body_accents: '',
}

export const sectionsForAdmin = [
	'dialogue',
	'culture',
	'legend',
	'slice-of-life',
	'place',
	'podcast',
	'book',
	'book-chapter',
	'short-story',
	'trailer',
	'extract',
	'cartoon',
	'eralash',
	'galileo',
	'diverse',
	'music',
]
