export const materials_ru = [
	{
		category: 'text & audio',
		newCategory: 'practice',
		img: 'dialogues.webp',
		title: 'dialogues',
		section: 'dialogues',
		text: 'Nos dialogues utilisent des tournures de phrases actuelles dans des situations variées. Ils vous aideront à maîtriser la langue parlée par les Russes au quotidien.',
	},
	{
		category: 'text & audio',
		newCategory: 'practice',
		img: 'slices-of-life.webp',
		title: 'tranches de vie',
		section: 'slices-of-life',
		text: 'Vous trouverez ici de courts récits autobiographiques qui vous apprendrons à parler de vous, de votre entourage, de vos goûts et de vos sentiments.',
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'beautiful-places.webp',
		title: 'beaux endroits',
		section: 'beautiful-places',
		text: "La Russie est un vaste pays qui compte parmi les plus beaux endroits de la planète. Nous vous emmenons pour une visite passionnante qui vous donnera l'occasion de pratiquer la langue tout en vous émerveillant.",
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'culture.webp',
		title: 'culture',
		section: 'culture',
		text: "La culture et le folklore changent d'un pays à l'autre et forgent l'identité des peuples. Dans cette section vous en saurez plus sur les particularités de la culture , du folklore et de l'artisanat russe.",
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'legends.webp',
		title: 'légendes et folklore',
		section: 'legends',
		text: "La culture et le folklore changent d'un pays à l'autre et forgent l'identité des peuples. Dans cette section vous en saurez plus sur les particularités de la culture , du folklore et de l'artisanat russe.",
	},
	{
		category: 'text & audio',
		newCategory: 'practice',
		img: 'podcasts.webp',
		title: 'podcasts',
		section: 'podcasts',
		text: 'Avec nos podcast apprenez-en plus sur les particularités de la langue russe.',
	},
	{
		category: 'text & audio',
		newCategory: 'literature',
		img: 'books.webp',
		title: 'livres audio',
		section: 'books',
		text: 'Ici vous trouverez des livres audio accompagnés de leur texte. Ainsi vous élargirez votre vocabulaire et améliorerez votre compréhension orale tout en voyageant dans le monde passionnant de la littérature.',
	},
	{
		category: 'text & audio',
		newCategory: 'literature',
		img: 'short-stories.webp',
		title: 'histoires courtes',
		section: 'short-stories',
		text: "Les histoires courtes ont le même objectif que les livres audio, mais sont plus condensées. Idéal pour ceux d'entre vous qui ne souhaitent pas se plonger dans un livre de plusieurs chapitres.",
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'movie-trailers.webp',
		title: 'bandes annonces',
		section: 'movie-trailers',
		text: "Avec les bandes annonces de films, vous disposez d'un moyen ludique pour vous entraîner à la compréhension orale du russe.",
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'movie-clips.webp',
		title: 'extraits de films',
		section: 'movie-clips',
		text: "Avec les extraits de films russes vous travaillerez votre compréhension de la langue telle que les Russes la parle au quotidien, faite d'idiomes, de jargon, mais surtout d'émotions.",
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'cartoons.webp',
		title: 'dessins animés',
		section: 'cartoons',
		text: "Les dessins animés russes font partie de la culture du pays. Les Russes y font souvent référence dans leurs conversations et les connaître vous permettra d'être considéré par les Russes comme l'un des leurs.",
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'eralash.webp',
		title: 'eralash',
		section: 'eralash',
		text: 'Eralash est une série de sketch humoristiques mettant en scène des enfants. Fraîches et drôles, ces petites saynètes vous feront apprendre dans la bonne humeur.',
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'galileo.webp',
		title: 'galileo',
		section: 'galileo',
		text: "Galileo est une émission de vulgarisation très populaire en Russie. Son présentateur déjanté y aborde des thèmes aussi variés que l'art, la science, la technologie, le sport, l'alimentation etc. Grâce à la grande variété des sujets traités, vous élargirez votre vocabulaire tout en vous cultivant.",
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'various-materials.webp',
		title: 'various materials',
		section: 'various-materials',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'rock.webp',
		title: 'rock',
		section: 'rock',
		text: "Ces chansons russes accompagnées de leur texte vous permettront d'apprendre tout en vous divertissant.",
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'pop.webp',
		title: 'pop',
		section: 'pop',
		text: "Les dessins animés russes font partie de la culture du pays. Les Russes y font souvent référence dans leurs conversations et les connaître vous permettra d'être considéré par les Russes comme l'un des leurs.",
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'folk.webp',
		title: 'trad/folk',
		section: 'folk',
		text: "Galileo est une émission de vulgarisation très populaire en Russie. Son présentateur déjanté y aborde des thèmes aussi variés que l'art, la science, la technologie, le sport, l'alimentation etc. Grâce à la grande variété des sujets traités, vous élargirez votre vocabulaire tout en vous cultivant.",
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'variety.webp',
		title: 'variété',
		section: 'variety',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'kids.webp',
		title: 'enfants',
		section: 'kids',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
]

export const materials_fr = [
	{
		category: 'text & audio',
		newCategory: 'practice',
		img: 'dialogues.webp',
		title: 'Диалоги',
		section: 'dialogues',
		text: 'Nos dialogues utilisent des tournures de phrases actuelles dans des situations variées. Ils vous aideront à maîtriser la langue parlée par les Russes au quotidien.',
	},
	{
		category: 'text & audio',
		newCategory: 'practice',
		img: 'slices-of-life.webp',
		title: 'Кусочки жизни',
		section: 'slices-of-life',
		text: 'Vous trouverez ici de courts récits autobiographiques qui vous apprendrons à parler de vous, de votre entourage, de vos goûts et de vos sentiments.',
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'beautiful-places.webp',
		title: 'Красивые места',
		section: 'beautiful-places',
		text: "La Russie est un vaste pays qui compte parmi les plus beaux endroits de la planète. Nous vous emmenons pour une visite passionnante qui vous donnera l'occasion de pratiquer la langue tout en vous émerveillant.",
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'culture.webp',
		title: 'Культура',
		section: 'culture',
		text: "La culture et le folklore changent d'un pays à l'autre et forgent l'identité des peuples. Dans cette section vous en saurez plus sur les particularités de la culture , du folklore et de l'artisanat russe.",
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'legends.webp',
		title: 'Фольклор и легенды',
		section: 'legends',
		text: "La culture et le folklore changent d'un pays à l'autre et forgent l'identité des peuples. Dans cette section vous en saurez plus sur les particularités de la culture , du folklore et de l'artisanat russe.",
	},
	{
		category: 'text & audio',
		newCategory: 'literature',
		img: 'books.webp',
		title: 'Аудиокниги',
		section: 'books',
		text: 'Ici vous trouverez des livres audio accompagnés de leur texte. Ainsi vous élargirez votre vocabulaire et améliorerez votre compréhension orale tout en voyageant dans le monde passionnant de la littérature.',
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'movie-trailers.webp',
		title: 'Трейлеры',
		section: 'movie-trailers',
		text: "Avec les bandes annonces de films, vous disposez d'un moyen ludique pour vous entraîner à la compréhension orale du russe.",
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'movie-clips.webp',
		title: 'Фрагменты из фильмов',
		section: 'movie-clips',
		text: "Avec les extraits de films russes vous travaillerez votre compréhension de la langue telle que les Russes la parle au quotidien, faite d'idiomes, de jargon, mais surtout d'émotions.",
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'cartoons.webp',
		title: 'Мультфильмы',
		section: 'cartoons',
		text: "Les dessins animés russes font partie de la culture du pays. Les Russes y font souvent référence dans leurs conversations et les connaître vous permettra d'être considéré par les Russes comme l'un des leurs.",
	},

	{
		category: 'video',
		newCategory: 'culture',
		img: 'various-materials.webp',
		title: 'Разное',
		section: 'various-materials',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'rock.webp',
		title: 'Рок',
		section: 'rock',
		text: "Ces chansons russes accompagnées de leur texte vous permettront d'apprendre tout en vous divertissant.",
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'pop.webp',
		title: 'Поп',
		section: 'pop',
		text: "Les dessins animés russes font partie de la culture du pays. Les Russes y font souvent référence dans leurs conversations et les connaître vous permettra d'être considéré par les Russes comme l'un des leurs.",
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'folk.webp',
		title: 'Традиционная музыка и Фольк',
		section: 'folk',
		text: "Galileo est une émission de vulgarisation très populaire en Russie. Son présentateur déjanté y aborde des thèmes aussi variés que l'art, la science, la technologie, le sport, l'alimentation etc. Grâce à la grande variété des sujets traités, vous élargirez votre vocabulaire tout en vous cultivant.",
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'variety.webp',
		title: 'Хиты',
		section: 'variety',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'kids.webp',
		title: 'Детские песни',
		section: 'kids',
		text: 'Vous retrouverez dans cette section des vidéos abordants des sujets variés et ne trouvant pas leur place dans les sections précédentes.',
	},
]

export const materials_en = [
	{
		category: 'text & audio',
		newCategory: 'practice',
		img: 'dialogues.webp',
		title: 'Dialogues',
		section: 'dialogues',
		text: 'Our dialogues use current phrases in various situations. They will help you master the language spoken by native speakers in everyday life.',
	},
	{
		category: 'text & audio',
		newCategory: 'practice',
		img: 'slices-of-life.webp',
		title: 'Slices of Life',
		section: 'slices-of-life',
		text: 'You will find here short autobiographical stories that will teach you to talk about yourself, your surroundings, your tastes and your feelings.',
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'beautiful-places.webp',
		title: 'Beautiful Places',
		section: 'beautiful-places',
		text: 'Discover beautiful places around the world. An exciting visit that will give you the opportunity to practice the language while marveling.',
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'legends.webp',
		title: 'Folklore and Legends',
		section: 'legends',
		text: 'Culture and folklore change from one country to another and shape the identity of peoples. In this section you will learn more about the particularities of culture, folklore and crafts.',
	},
	{
		category: 'text & audio',
		newCategory: 'literature',
		img: 'books.webp',
		title: 'Audiobooks',
		section: 'books',
		text: 'Here you will find audiobooks accompanied by their text. This way you will expand your vocabulary and improve your listening comprehension while traveling in the exciting world of literature.',
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'movie-trailers.webp',
		title: 'Movie Trailers',
		section: 'movie-trailers',
		text: 'With movie trailers, you have a fun way to practice your listening comprehension.',
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'movie-clips.webp',
		title: 'Movie Clips',
		section: 'movie-clips',
		text: 'With movie clips you will work on your understanding of the language as native speakers speak it in everyday life, made of idioms, jargon, but above all emotions.',
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'cartoons.webp',
		title: 'Cartoons',
		section: 'cartoons',
		text: 'Cartoons are part of the culture. Knowing them will allow you to be considered by native speakers as one of their own.',
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'various-materials.webp',
		title: 'Various',
		section: 'various-materials',
		text: 'You will find in this section videos covering various subjects that do not find their place in the previous sections.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'rock.webp',
		title: 'Rock',
		section: 'rock',
		text: 'These songs accompanied by their lyrics will allow you to learn while having fun.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'pop.webp',
		title: 'Pop',
		section: 'pop',
		text: 'Popular music accompanied by lyrics to help you learn while enjoying great songs.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'folk.webp',
		title: 'Traditional Music & Folk',
		section: 'folk',
		text: 'Traditional and folk music to discover cultural heritage while learning the language.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'variety.webp',
		title: 'Hits',
		section: 'variety',
		text: 'Popular hits and variety songs to practice your listening skills while enjoying great music.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'kids.webp',
		title: 'Kids Songs',
		section: 'kids',
		text: 'Fun and educational songs for children and beginners.',
	},
]

export const materials_it = [
	{
		category: 'text & audio',
		newCategory: 'practice',
		img: 'dialogues.webp',
		title: 'Dialoghi',
		section: 'dialogues',
		text: 'I nostri dialoghi utilizzano espressioni attuali in situazioni varie. Ti aiuteranno a padroneggiare la lingua parlata dagli italiani nella vita quotidiana.',
	},
	{
		category: 'text & audio',
		newCategory: 'practice',
		img: 'slices-of-life.webp',
		title: 'Momenti di vita',
		section: 'slices-of-life',
		text: 'Qui troverai brevi racconti autobiografici che ti insegneranno a parlare di te, del tuo ambiente, dei tuoi gusti e dei tuoi sentimenti.',
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'beautiful-places.webp',
		title: 'Luoghi incantevoli',
		section: 'beautiful-places',
		text: "L'Italia è un paese ricco di luoghi meravigliosi. Ti porteremo in un viaggio affascinante che ti darà l'opportunità di praticare la lingua mentre ti meravigli.",
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'culture.webp',
		title: 'Cultura',
		section: 'culture',
		text: "La cultura e il folklore cambiano da un paese all'altro e forgiano l'identità dei popoli. In questa sezione scoprirai di più sulle particolarità della cultura e del folklore italiano.",
	},
	{
		category: 'text & audio',
		newCategory: 'culture',
		img: 'legends.webp',
		title: 'Folklore e leggende',
		section: 'legends',
		text: "Le leggende e il folklore italiano sono ricchi di storie affascinanti. Scopri le tradizioni che hanno plasmato l'identità del paese.",
	},
	{
		category: 'text & audio',
		newCategory: 'literature',
		img: 'books.webp',
		title: 'Audiolibri',
		section: 'books',
		text: 'Qui troverai audiolibri accompagnati dal loro testo. Così amplierai il tuo vocabolario e migliorerai la comprensione orale viaggiando nel mondo affascinante della letteratura italiana.',
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'movie-trailers.webp',
		title: 'Trailer',
		section: 'movie-trailers',
		text: "Con i trailer dei film, hai un modo divertente per esercitarti nella comprensione orale dell'italiano.",
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'movie-clips.webp',
		title: 'Scene di film',
		section: 'movie-clips',
		text: 'Con gli estratti di film italiani lavorerai sulla tua comprensione della lingua come la parlano gli italiani nella vita quotidiana, fatta di modi di dire, gergo, ma soprattutto emozioni.',
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'cartoons.webp',
		title: 'Cartoni animati',
		section: 'cartoons',
		text: 'I cartoni animati fanno parte della cultura italiana. Conoscerli ti permetterà di sentirti più vicino alla cultura del paese.',
	},
	{
		category: 'video',
		newCategory: 'culture',
		img: 'various-materials.webp',
		title: 'Vari',
		section: 'various-materials',
		text: 'In questa sezione troverai video su argomenti vari che non trovano posto nelle sezioni precedenti.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'rock.webp',
		title: 'Rock',
		section: 'rock',
		text: 'Queste canzoni italiane accompagnate dal loro testo ti permetteranno di imparare divertendoti.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'pop.webp',
		title: 'Pop',
		section: 'pop',
		text: 'La musica pop italiana accompagnata dai testi per aiutarti a imparare mentre ascolti grandi canzoni.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'folk.webp',
		title: 'Musica tradizionale e Folk',
		section: 'folk',
		text: 'Musica tradizionale e folk per scoprire il patrimonio culturale italiano mentre impari la lingua.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'variety.webp',
		title: 'Successi',
		section: 'variety',
		text: 'Successi e canzoni popolari per praticare le tue abilità di ascolto mentre ascolti ottima musica.',
	},
	{
		category: 'music',
		newCategory: 'culture',
		img: 'kids.webp',
		title: 'Canzoni per bambini',
		section: 'kids',
		text: 'Canzoni divertenti ed educative per bambini e principianti.',
	},
]

export const lang = ['ru', 'fr', 'en', 'it']
export const level = ['beginner', 'intermediate', 'advanced']
export const postData = {
	lang: '',
	title: '',
	img: '',
	body: '',
	description: '',
}

export const materialData = {
	lang: '',
	section: '',
	book_id: '',
	chapter_number: '',
	level: '',
	title: '',
	image_filename: '',
	audio_filename: '',
	video_url: '',
	content: '',
	content_accented: '',
}

// Sections avec audio (text & audio)
export const audioSections = [
	'dialogues',
	'culture',
	'legends',
	'slices-of-life',
	'beautiful-places',
	'podcasts',
	'short-stories',
	'book-chapters',
]

// Sections avec vidéo
export const videoSections = [
	'movie-trailers',
	'movie-clips',
	'cartoons',
	'eralash',
	'galileo',
	'various-materials',
	'rock',
	'pop',
	'folk',
	'variety',
	'kids',
]

export const sectionsForAdmin = [
	'dialogues',
	'culture',
	'legends',
	'slices-of-life',
	'beautiful-places',
	'podcasts',
	'short-stories',
	'book-chapters',
	'movie-trailers',
	'movie-clips',
	'cartoons',
	'eralash',
	'galileo',
	'various-materials',
	'rock',
	'pop',
	'folk',
	'variety',
	'kids',
]
